// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_riverpod_template/features/qr_scanner/domain/scan_record.dart';
import 'package:flutter_riverpod_template/features/qr_scanner/domain/scan_type.dart';
import 'package:flutter_riverpod_template/features/user_profile/domain/user_profile.dart';
import 'package:flutter_riverpod_template/features/user_profile/domain/user_role.dart';
import 'package:flutter_riverpod_template/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LoginCredentialsAdapter());
    registerAdapter(ScanRecordAdapter());
    registerAdapter(ScanRecordAdapter());
    registerAdapter(ScanTypeAdapter());
    registerAdapter(ScanTypeAdapter());
    registerAdapter(ThemeUiModelAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(UserRoleAdapter());
    registerAdapter(UserRoleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LoginCredentialsAdapter());
    registerAdapter(ScanRecordAdapter());
    registerAdapter(ScanRecordAdapter());
    registerAdapter(ScanTypeAdapter());
    registerAdapter(ScanTypeAdapter());
    registerAdapter(ThemeUiModelAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(UserProfileAdapter());
    registerAdapter(UserRoleAdapter());
    registerAdapter(UserRoleAdapter());
  }
}
